# Generated by Django 5.2.4 on 2025-07-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_partnership_date_joined_partnership_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepage',
            name='date_added',
            field=models.DateField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursepage',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='date_added',
            field=models.DateField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
