# Generated by Django 5.2.4 on 2025-07-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnership',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnership',
            name='last_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
