# Generated by Django 5.2.4 on 2025-07-26 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursepage_date_added_coursepage_last_modified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Instructors',
            new_name='instructors',
        ),
    ]
