# Generated by Django 5.2.4 on 2025-07-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_instructor_name_alter_partnership_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepage',
            name='featured_courses',
            field=models.ManyToManyField(related_name='featured_courses', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='top_rated_courses',
            field=models.ManyToManyField(related_name='top_rated_courses', to='courses.course'),
        ),
    ]
