# Generated by Django 5.2.4 on 2025-08-13 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JoinForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter valid phone number.', regex='^\\+?\\d{7,15}$')])),
                ('course_interested_in', models.CharField(choices=[('data_engineering', 'Data Engineering'), ('ai_python_beginners', 'AI Python for Beginners'), ('generative_ai_software', 'Generative AI for Software Development'), ('dspy_agentic_apps', 'DSPy: Build and Optimize Agentic Apps'), ('orchestrating_workflows', 'Orchestrating Workflows for GenAI Applications'), ('structured_llm_output', 'Getting Structured LLM Output'), ('advanced_prompt_engineering', 'Advanced Prompt Engineering'), ('ai_business_leaders', 'AI for Business Leaders'), ('machine_learning_foundations', 'Machine Learning Foundations'), ('full_stack_ai', 'Full Stack AI Applications')], help_text="Select the course you're interested in", max_length=50)),
                ('highest_qualification', models.CharField(choices=[('high_school', 'High School'), ('diploma', 'Diploma'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD'), ('other', 'Other')], default='bachelor', max_length=50)),
                ('skills', models.TextField(help_text='List your technical skills')),
                ('linkedin_profile', models.URLField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Join Form Application',
                'verbose_name_plural': 'Join Form Applications',
                'ordering': ['-date_submitted'],
            },
        ),
    ]
